
version: 2

models:
  - name: fast_vehicles
    description: "Query fast vehicles"
    
  - name: vehicles_summary
    description: "A summary of vehicles by distance and speed"
  
  - name: fast_vehicles_summary
    description: "A summary of vehicles by distance and speed"

  - name: timely_summary
    description: "A summary of vehicles by speed"

  - name: speed_timely_summary
    description: "A summary of vehicles by distance and speed"

  - name: lat_timely_summary
    description: "A summary of vehicles by distance and speed"

  - name: lon_timely_summary
    description: "A summary of vehicles by distance and speed"

  - name: ten_vehicles
    description: "A summary of vehicles by distance and speed"





  # - name: reverse_geocoding
  
  # #   # Document within the same codebase
  #   description: My transformation written in Python
    
  # #   # Configure in ways that feel intuitive and familiar
  #   config:
  #     materialized: view
  #     tags: ['python']  